apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: concourse-ingress
  annotations:
    certmanager.k8s.io/issuer: "lets-encrypt-staging"
spec:
  tls:
  - hosts:
    - concourse.morsley.io
    secretName: lets-encrypt-staging
  rules:
  - host: concourse.morsley.io
    http:
      paths:
      - path: /
        backend:
          serviceName: concourse-web
          servicePort: 8080