apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: concourse-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "lets-encrypt-test"
#    nginx.ingress.kubernetes.io/secure-backends: "true"
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - concourse.morsley.io
    secretName: lets-encrypt-tls-test
  rules:
  - host: concourse.morsley.io
    http:
      paths:
      - path: /
        backend:
          serviceName: concourse-web
          servicePort: 8080