apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: concourse-ingress
spec:
  rules:
    - host: concourse.morsley.io
      http:
        paths:
          - backend:
              serviceName: concourse-web.concourse.svc.cluster.local
              servicePort: 8080