apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: concourse-morsley-io-lets-encrypt
spec:
  secretName: lets-encrypt-tls-staging-test
  issuerRef:
    name: lets-encrypt-staging
  commonName: concourse.morsley.io
  acme: 
    config:
      - http01:
          ingress: concourse-ingress
        domains:
          - concourse.morsley.io